<?php
return [
    'status' => [
        'pending' => 0,
        'active' => 1,
        'disabled' => 2,
    ],
    'category' => [
        [
            'id' => 1,
            'name' => 'Ads board',
            'slug' => 'ads-board',
            'description' => "",
            'keywords' => "",
        ],
        [
            'id' => 2,
            'name' => 'Media',
            'slug' => 'media',
            'description' => "",
            'keywords' => "",
        ],
        [
            'id' => 3,
            'name' => 'Digital Marketing',
            'slug' => 'digital-marketing',
            'description' => "",
            'keywords' => "",
        ],
        [
            'id' => 4,
            'name' => 'Ads banner',
            'slug' => 'ads-banner',
            'description' => "",
            'keywords' => "",
        ],
        [
            'id' => 5,
            'name' => 'Ads Work',
            'slug' => 'ads-work',
            'description' => "",
            'keywords' => "",
        ],
        [
            'id' => 6,
            'name' => 'Need',
            'slug' => 'need',
            'description' => "",
            'keywords' => "",
        ],
    ],
    'provider' => [
        ['id' => 1, 'name' => 'Cá nhân'],
        ['id' => 2, 'name' => 'Tổ chức'],
        ['id' => 3, 'name' => 'Doanh nghiệp'],
        ['id' => 4, 'name' => 'Nhà nước'],
    ],
    'price_range' => [
        ['id' => 1, 'name' => '0M - 3M'],
        ['id' => 2, 'name' => '3M - 5M'],
        ['id' => 3, 'name' => '5M - 10M'],
        ['id' => 4, 'name' => '>10M'],
        ['id' => 5, 'name' => '>50M'],
        ['id' => 6, 'name' => '>100M'],
        ['id' => 7, 'name' => '>500M'],
        ['id' => 8, 'name' => 'Thoả thuận'],
    ],
    'pano' => [
        'type' => [
            ['id' => 1, 'name' => 'Tĩnh'],
            ['id' => 2, 'name' => 'Động'],
            ['id' => 3, 'name' => 'LED'],
        ],
        'size' => [
            ['id' => 1, 'name' => 'Dưới 5m2'],
            ['id' => 2, 'name' => 'Trên 5m2'],
            ['id' => 3, 'name' => 'Trên 10m2'],
            ['id' => 4, 'name' => 'Trên 20m2'],
            ['id' => 5, 'name' => 'Trên 50m2'],
        ],
        'border' => [
            ['id' => 1, 'name' => 'Đã dựng'],
            ['id' => 2, 'name' => 'Chưa dựng'],
        ],
        'light' => [
            ['id' => 1, 'name' => 'Vào buổi tối'],
            ['id' => 2, 'name' => '24/24'],
            ['id' => 3, 'name' => 'Không có'],
        ],
    ],
    'ad' => [
        'channel' => [
            ['id' => 1, 'name' => 'Truyền hình tương tự (Analog)'],
            ['id' => 2, 'name' => 'Truyền hình số (Digital)'],
            ['id' => 3, 'name' => 'Truyền hình số mặt đất (DVB-T2)'],
            ['id' => 4, 'name' => 'Truyền hình số hữu tuyến (DVB-C2)'],
            ['id' => 5, 'name' => 'Truyền hình cáp (cable)'],
            ['id' => 6, 'name' => 'Truyền hình số vệ tinh (DVB-S2)'],
            ['id' => 7, 'name' => 'Truyền hình internet (IPTV)'],
            ['id' => 8, 'name' => 'Truyền hình khác'],
            ['id' => 9, 'name' => 'FM radio'],
            ['id' => 10, 'name' => 'AM radio'],
            ['id' => 11, 'name' => 'Phát thanh khác'],
        ],
        'coverage' => [
            ['id' => 1, 'name' => 'Theo tỉnh'],
            ['id' => 2, 'name' => 'Kênh trung ương'],
            ['id' => 3, 'name' => 'Toàn quốc'],
        ],
        'time' => [
            ['id' => 1, 'name' => '0 - 30 giây'],
            ['id' => 2, 'name' => '30 - 60 giây'],
            ['id' => 3, 'name' => '60 - 300 giây'],
            ['id' => 4, 'name' => '>5 phút'],
        ],
    ],
    'social' => [
        'type' => [
            ['id' => 1, 'name' => 'Quảng cáo Facebook Ads'],
            ['id' => 2, 'name' => 'Quảng cáo trên trang HOT'],
            ['id' => 3, 'name' => 'Quảng cáo trên fanpage'],
            ['id' => 4, 'name' => 'Quảng cáo trên trang cá nhân'],
            ['id' => 5, 'name' => 'Quảng cáo livestream '],
            ['id' => 6, 'name' => 'Quảng cáo khác'],
            ['id' => 7, 'name' => 'Quảng cáo Google Ads'],
            ['id' => 8, 'name' => 'Quảng cáo khác '],
            ['id' => 9, 'name' => 'Quảng cáo Youtube Ads'],
            ['id' => 10, 'name' => 'Video kênh HOT'],
            ['id' => 11, 'name' => 'Video kênh cá nhân '],
            ['id' => 12, 'name' => 'Video kênh thông tin, giải trí'],
            ['id' => 13, 'name' => 'Video kênh văn hoá, xã hội '],
            ['id' => 14, 'name' => 'Video kênh game, công nghệ '],
            ['id' => 15, 'name' => 'Video kênh thể thao, du lịch '],
            ['id' => 16, 'name' => 'Quảng cáo livestream '],
            ['id' => 17, 'name' => 'Quảng cáo Youtube khác'],
            ['id' => 18, 'name' => 'Vị trí logo, banner'],
            ['id' => 19, 'name' => 'Mục đăng tin '],
            ['id' => 20, 'name' => 'Bài viết review '],
            ['id' => 21, 'name' => 'Bài viết định hướng'],
            ['id' => 22, 'name' => 'Quảng cáo khác'],
        ],
        'follow' => [
            ['id' => 1, 'name' => 'Dưới 500.000'],
            ['id' => 2, 'name' => 'Trên 500.000'],
            ['id' => 3, 'name' => 'Trên 1 triệu'],
            ['id' => 4, 'name' => 'Trên 2 triệu'],
            ['id' => 5, 'name' => 'Trên 5 triệu'],
        ],
    ],
    'web' => [
        'type' => [
            ['id' => 3, 'name' => 'Máy tính và di động'],
            ['id' => 1, 'name' => 'Máy tính'],
            ['id' => 2, 'name' => 'Thiết bị di động'],
        ],
        'position' => [
            ['id' => 1, 'name' => 'Toàn thời gian'],
            ['id' => 2, 'name' => 'Trang chủ'],
            ['id' => 3, 'name' => 'Trang con'],
        ],
    ],
    'find' => [
        'service' => [
            ['id' => 1, 'name' => 'Cho thuê vị trí'],
            ['id' => 2, 'name' => 'Thi công, lắp đặt'],
            ['id' => 3, 'name' => 'Thiết kế'],
            ['id' => 4, 'name' => 'In ấn'],
            ['id' => 5, 'name' => 'SEO'],
            ['id' => 6, 'name' => 'Quay phim'],
            ['id' => 7, 'name' => 'Chụp ảnh'],
            ['id' => 8, 'name' => 'Seeding'],
            ['id' => 9, 'name' => 'Viết bài'],
            ['id' => 10, 'name' => 'Dịch vụ cần tìm khác'],
        ],
    ],
];

